export const foodOptions = [
  { name: "Huevos (2 piezas)", calories: 140 },
  { name: "Pan integral (2 rebanadas)", calories: 120 },
  { name: "Avena (1 taza cocida)", calories: 150 },
  { name: "Leche descremada (1 taza)", calories: 90 },
  { name: "Yogur natural (1 taza)", calories: 100 },
  { name: "Banana (1 mediana)", calories: 105 },
  { name: "Manzana (1 mediana)", calories: 95 },
  { name: "Naranja (1 mediana)", calories: 60 },
  { name: "Fresas (1 taza)", calories: 50 },
  { name: "Arroz blanco (1 taza cocido)", calories: 200 },
  { name: "Pasta cocida (1 taza)", calories: 220 },
  { name: "Pollo a la plancha (100g)", calories: 165 },
  { name: "Carne de res magra (100g)", calories: 250 },
  { name: "Pescado (100g)", calories: 180 },
  { name: "Tofu (100g)", calories: 80 },
  { name: "Aguacate (1 mediano)", calories: 240 },
  { name: "Queso cheddar (30g)", calories: 120 },
  { name: "Almendras (30g)", calories: 170 },
  { name: "Nueces (30g)", calories: 200 },
  { name: "Cacahuates (30g)", calories: 170 },
  { name: "Aceite de oliva (1 cucharada)", calories: 120 },
  { name: "Mantequilla (1 cucharada)", calories: 100 },
  { name: "Sopa de verduras (1 taza)", calories: 80 },
  { name: "Ensalada con aderezo ligero", calories: 150 },
  { name: "Papas al horno (1 mediana)", calories: 160 },
  { name: "Camote (1 mediano)", calories: 130 },
  { name: "Zanahoria (1 mediana)", calories: 25 },
  { name: "Brócoli (1 taza cocido)", calories: 55 },
  { name: "Espinaca (1 taza cocida)", calories: 40 },
  { name: "Galletas integrales (2 piezas)", calories: 70 },
  { name: "Chocolate negro (30g)", calories: 170 },
  { name: "Helado (1/2 taza)", calories: 140 },
  { name: "Refresco (1 lata)", calories: 150 },
  { name: "Agua", calories: 0 },
  { name: "Café negro", calories: 5 },
  { name: "Té verde", calories: 5 },
];
